### ISSUE TITLE
Double check that logger works on Airnode (lambda)

### ISSUE THREAD

**Issue by Siegrift** [api3dao/commons#11]
See: https://github.com/api3dao/commons/pull/8#discussion_r1350390646

- If it does not, we should document so in the README or make it more platform agnostic.
- Ideally, we should check on both GCP and AWS

**Comment by Siegrift** [comment]
@aquarat I think the logger will work on lambda without any issues. I think migrating the logger in Airnode is a very large task so I am thinking that before doing that we should do a quick check. Maybe not even in Airnode, but just on a simple node.js script deployed on AWS and GCP and seeing that the logger works.

I think the migration in Airnode would be a natural followup. WDYT?

**Comment by aquarat** [comment]
The logger works on AWS, GCP and in the console.

I did [a basic swap-out of the logger in airnode-utilities](https://github.com/api3dao/airnode/blob/replace-logger-in-airnode-with-commons/packages/airnode-utilities/src/logging/logging.ts) and then deployed airnode to AWS and GCP.

<img width="1457" alt="Screenshot 2023-12-27 at 15 56 17" src="https://github.com/api3dao/commons/assets/3090997/add1748f-203e-4ca6-a47a-243bad8f04ee">

<img width="1552" alt="Screenshot 2023-12-27 at 16 20 14" src="https://github.com/api3dao/commons/assets/3090997/56c4c198-cb35-40f8-9d1b-cd1e9e2a4fe9">

You can tell it's the logger due to the double-timestamping.
