### ISSUE TITLE
Implement env variable (secrets) parsing

### ISSUE THREAD

**Issue by andreogle** [api3dao/commons#43]
A common usecase is interpolating secrets (e.g. in the [signed API](https://github.com/api3dao/signed-api/pull/199)). Extract these functions for easier and consistent use.

**Comment by Siegrift** [comment]
Note, that there are [multiple projects which use secrets parsing](https://github.com/search?q=org%3Aapi3dao%20ES_MATCH_REGEXP&type=code) (also click the "show identical" at the bottom of search results page). There are also many which use the broken version reported [here](https://github.com/api3dao/signed-api/issues/234).

After the fix is released each project should have an issue opened to migrate to commons instead.
